CREATE DATABASE Accounting
GO

USE Accounting
GO

CREATE TABLE Countries(
Id INT IDENTITY PRIMARY KEY,
[Name] VARCHAR(10) NOT NULL
);

CREATE TABLE Addresses(
Id INT IDENTITY PRIMARY KEY,
StreetName NVARCHAR(20) NOT NULL,
StreetNumber INT,
PostCode INT NOT NULL,
City VARCHAR(25) NOT NULL,
CountryId INT FOREIGN KEY REFERENCES Countries(Id) NOT NULL
);

CREATE TABLE Vendors(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(25) NOT NULL,
NumberVAT NVARCHAR(15) NOT NULL,
AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL
);

CREATE TABLE Clients (
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(25) NOT NULL,
NumberVAT NVARCHAR (15) NOT NULL,
AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL
);

CREATE TABLE Categories (
Id INT IDENTITY PRIMARY KEY,
[Name] VARCHAR(10) NOT NULL
);

CREATE TABLE Products (
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(35) NOT NULL,
Price DECIMAL(18,2) NOT NULL,
CategoryId INT FOREIGN KEY REFERENCES Categories(Id) NOT NULL,
VendorId INT FOREIGN KEY REFERENCES Vendors(Id) NOT NULL
)

CREATE TABLE Invoices (
Id INT IDENTITY PRIMARY KEY,
Number INT UNIQUE NOT NULL,
IssueDate DATETIME2 NOT NULL,
DueDate DATETIME2 NOT NULL,
Amount DECIMAL (18,2) NOT NULL,
Currency VARCHAR(5) NOT NULL,
ClientId INT FOREIGN KEY REFERENCES Clients(Id) NOT NULL
);

CREATE TABLE ProductsClients (
ProductId INT NOT NULL FOREIGN KEY REFERENCES Products(Id),
ClientId INT NOT NULL FOREIGN KEY REFERENCES Clients(Id),
CONSTRAINT PK_ProductsClients PRIMARY KEY(ProductId, ClientId)
);