CREATE DATABASE OnlineStore
GO

USE OnlineStore

CREATE TABLE Cities
(
CityID INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR (50) NOT NULL
)

CREATE TABLE ItemTypes
(
ItemTypeID INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR (50) NOT NULL
)

CREATE TABLE Customers
(
CustomerID INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR (50) NOT NULL,
Birthday DATETIME2 NOT NULL,
CityID INT NOT NULL FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Items
(
ItemID INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR (50) NOT NULL,
ItemTypeID INT NOT NULL FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE Orders
(
OrderID INT PRIMARY KEY IDENTITY,
CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE OrderItems
(
OrderID INT FOREIGN KEY REFERENCES Orders(OrderID),
ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
PRIMARY KEY (OrderID, ItemID)
)